const audi = [
  {title: "100", value: "100"},
  {title: "200", value: "200"},
  {title: "4000", value: "4000"},
  {title: "50", value: "50"},
  {title: "5000", value: "5000"},
  {title: "80", value: "80"},
  {title: "90", value: "90"},
  {title: "A1", value: "A1"},
  {title: "A2", value: "A2"},
  {title: "A3", value: "A3"},
  {title: "A3 e-tron", value: "A3 e-tron"},
  {title: "A4", value: "A4"},
  {title: "A5", value: "A5"},
  {title: "A6", value: "A6"},
  {title: "A7", value: "A7"},
  {title: "A8", value: "A8"},
  {title: "AD", value: "AD"},
  {title: "AL2", value: "AL2"},
  {title: "Allroad", value: "Allroad"},
  {title: "Asso", value: "Asso"},
  {title: "Avantissimo", value: "Avantissimo"},
  {title: "Avus", value: "Avus"},
  {title: "Coupe", value: "Coupe"},
  {title: "Fox", value: "Fox"},
  {title: "LeMans", value: "LeMans"},
  {title: "Nuvolari Quattro", value: "Nuvolari Quattro"},
  {title: "Pikes Peak Quattro", value: "Pikes Peak Quattro"},
  {title: "Q3", value: "Q3"},
  {title: "Q5", value: "Q5"},
  {title: "Q7", value: "Q7"},
  {title: "Quattro", value: "Quattro"},
  {title: "R8", value: "R8"},
  {title: "R8R", value: "R8R"},
  {title: "Rosemeyer", value: "Rosemeyer"},
  {title: "RS 5", value: "RS 5"},
  {title: "RS 7", value: "RS 7"},
  {title: "RS2", value: "RS2"},
  {title: "RS3", value: "RS3"},
  {title: "RS4", value: "RS4"},
  {title: "RS5", value: "RS5"},
  {title: "RS6", value: "RS6"},
  {title: "S2", value: "S2"},
  {title: "S3", value: "S3"},
  {title: "S4", value: "S4"},
  {title: "S5", value: "S5"},
  {title: "S6", value: "S6"},
  {title: "S7", value: "S7"},
  {title: "S8", value: "S8"},
  {title: "Sport", value: "Sport"},
  {title: "SQ5", value: "SQ5"},
  {title: "Steppenwolf", value: "Steppenwolf"},
  {title: "Super 90", value: "Super 90"},
  {title: "TT", value: "TT"},
  {title: "TTS", value: "TTS"},
  {title: "UR", value: "UR"},
  {title: "V8", value: "V8"},
  {title: "Variant", value: "Variant"},
];

const bmw = [
  {title: "1 Series", value: "1 Series"},
  {title: "116", value: "116"},
  {title: "118", value: "118"},
  {title: "120", value: "120"},
  {title: "123", value: "123"},
  {title: "125", value: "125"},
  {title: "128", value: "128"},
  {title: "130", value: "130"},
  {title: "135", value: "135"},
  {title: "1500", value: "1500"},
  {title: "1502", value: "1502"},
  {title: "1600", value: "1600"},
  {title: "1602", value: "1602"},
  {title: "1800", value: "1800"},
  {title: "2 Series", value: "2 Series"},
  {title: "2.8", value: "2.8"},
  {title: "2000", value: "2000"},
  {title: "2002", value: "2002"},
  {title: "2004", value: "2004"},
  {title: "2800", value: "2800"},
  {title: "3", value: "3"},
  {title: "3 Series", value: "3 Series"},
  {title: "3 Series Gran Turismo", value: "3 Series Gran Turismo"},
  {title: "3.3", value: "3.3"},
  {title: "315", value: "315"},
  {title: "316", value: "316"},
  {title: "317", value: "317"},
  {title: "318", value: "318"},
  {title: "320", value: "320"},
  {title: "3200 CS", value: "3200 CS"},
  {title: "323", value: "323"},
  {title: "324", value: "324"},
  {title: "325", value: "325"},
  {title: "328", value: "328"},
  {title: "330", value: "330"},
  {title: "332", value: "332"},
  {title: "333", value: "333"},
  {title: "335", value: "335"},
  {title: "340", value: "340"},
  {title: "4 Series", value: "4 Series"},
  {title: "4 Series Gran Coupe", value: "4 Series Gran Coupe"},
  {title: "5 Series", value: "5 Series"},
  {title: "5 Series Gran Turismo", value: "5 Series Gran Turismo"},
  {title: "5.8", value: "5.8"},
  {title: "501", value: "501"},
  {title: "502", value: "502"},
  {title: "503", value: "503"},
  {title: "507", value: "507"},
  {title: "518", value: "518"},
  {title: "520", value: "520"},
  {title: "523", value: "523"},
  {title: "524", value: "524"},
  {title: "525", value: "525"},
  {title: "528", value: "528"},
  {title: "529", value: "529"},
  {title: "530", value: "530"},
  {title: "535", value: "535"},
  {title: "538", value: "538"},
  {title: "540", value: "540"},
  {title: "545", value: "545"},
  {title: "550", value: "550"},
  {title: "6 series", value: "6 series"},
  {title: "6 Series Gran Coupe", value: "6 Series Gran Coupe"},
  {title: "600", value: "600"},
  {title: "628", value: "628"},
  {title: "630", value: "630"},
  {title: "633", value: "633"},
  {title: "635", value: "635"},
  {title: "640", value: "640"},
  {title: "645", value: "645"},
  {title: "650", value: "650"},
  {title: "7 Series", value: "7 Series"},
  {title: "700", value: "700"},
  {title: "725", value: "725"},
  {title: "728", value: "728"},
  {title: "729", value: "729"},
  {title: "730", value: "730"},
  {title: "732", value: "732"},
  {title: "735", value: "735"},
  {title: "740", value: "740"},
  {title: "745", value: "745"},
  {title: "748", value: "748"},
  {title: "750", value: "750"},
  {title: "760", value: "760"},
  {title: "840", value: "840"},
  {title: "845", value: "845"},
  {title: "850", value: "850"},
  {title: "854", value: "854"},
  {title: "856", value: "856"},
  {title: "ActiveHybrid 3", value: "ActiveHybrid 3"},
  {title: "ActiveHybrid 5", value: "ActiveHybrid 5"},
  {title: "ActiveHybrid 7", value: "ActiveHybrid 7"},
  {title: "Alpina", value: "Alpina"},
  {title: "ALPINA B6 Gran Coupe", value: "ALPINA B6 Gran Coupe"},
  {title: "ALPINA B7", value: "ALPINA B7"},
  {title: "B7", value: "B7"},
  {title: "Breyton", value: "Breyton"},
  {title: "CLS", value: "CLS"},
  {title: "Compact", value: "Compact"},
  {title: "Convertible", value: "Convertible"},
  {title: "Coupe", value: "Coupe"},
  {title: "Dinan", value: "Dinan"},
  {title: "Formula FB02", value: "Formula FB02"},
  {title: "Formula One", value: "Formula One"},
  {title: "FW 27", value: "FW 27"},
  {title: "Isetta", value: "Isetta"},
  {title: "Just 4", value: "Just 4"},
  {title: "Karmann Asso di Quadri", value: "Karmann Asso di Quadri"},
  {title: "L7", value: "L7"},
  {title: "LMR", value: "LMR"},
  {title: "M", value: "M"},
  {title: "M1", value: "M1"},
  {title: "M12", value: "M12"},
  {title: "M28i", value: "M28i"},
  {title: "M3", value: "M3"},
  {title: "M4", value: "M4"},
  {title: "M5", value: "M5"},
  {title: "M6", value: "M6"},
  {title: "M6 Gran Coupe", value: "M6 Gran Coupe"},
  {title: "Mini ACV 30", value: "Mini ACV 30"},
  {title: "MM Roadster", value: "MM Roadster"},
  {title: "Pickster", value: "Pickster"},
  {title: "S3", value: "S3"},
  {title: "Touring", value: "Touring"},
  {title: "Turbo", value: "Turbo"},
  {title: "V12", value: "V12"},
  {title: "Veritas Rennsportwagen", value: "Veritas Rennsportwagen"},
  {title: "X Activity", value: "X Activity"},
  {title: "X Coupe", value: "X Coupe"},
  {title: "X1", value: "X1"},
  {title: "X3", value: "X3"},
  {title: "X4", value: "X4"},
  {title: "X5", value: "X5"},
  {title: "X5 M", value: "X5 M"},
  {title: "X6", value: "X6"},
  {title: "X6 M", value: "X6 M"},
  {title: "Z1", value: "Z1"},
  {title: "Z18", value: "Z18"},
  {title: "Z22", value: "Z22"},
  {title: "Z3", value: "Z3"},
  {title: "Z4", value: "Z4"},
  {title: "Z8", value: "Z8"},
  {title: "Z9", value: "Z9"},
  {title: "Z9 Gran Turismo Convertible", value: "Z9 Gran Turismo Convertible"},
];

const buick = [
  {title: "40", value: "40"},
  {title: "70", value: "70"},
  {title: "Blackhawk", value: "Blackhawk"},
  {title: "Centieme", value: "Centieme"},
  {title: "Centurion", value: "Centurion"},
  {title: "Century", value: "Century"},
  {title: "Cielo", value: "Cielo"},
  {title: "Electra", value: "Electra"},
  {title: "Enclave", value: "Enclave"},
  {title: "Encore", value: "Encore"},
  {title: "Estate", value: "Estate"},
  {title: "GS", value: "GS"},
  {title: "Invicta", value: "Invicta"},
  {title: "LaCrosse", value: "LaCrosse"},
  {title: "LeSabre", value: "LeSabre"},
  {title: "Lucerne", value: "Lucerne"},
  {title: "Park Avenue", value: "Park Avenue"},
  {title: "Rainier", value: "Rainier"},
  {title: "Reatta", value: "Reatta"},
  {title: "Regal", value: "Regal"},
  {title: "Rendezvous", value: "Rendezvous"},
  {title: "Riviera", value: "Riviera"},
  {title: "Roadmaster", value: "Roadmaster"},
  {title: "Signia", value: "Signia"},
  {title: "Skyhawk", value: "Skyhawk"},
  {title: "Skylark", value: "Skylark"},
  {title: "Terraza", value: "Terraza"},
  {title: "Verano", value: "Verano"},
  {title: "Wildcat", value: "Wildcat"},
  {title: "XP2000", value: "XP2000"},
];

const cadillac = [
  {title: "60", value: "60"},
  {title: "61", value: "61"},
  {title: "62", value: "62"},
  {title: "6239D", value: "6239D"},
  {title: "Allante", value: "Allante"},
  {title: "ATS", value: "ATS"},
  {title: "ATS Coupe", value: "ATS Coupe"},
  {title: "Aurora", value: "Aurora"},
  {title: "Biarritz", value: "Biarritz"},
  {title: "BLS", value: "BLS"},
  {title: "Brougham", value: "Brougham"},
  {title: "Calais", value: "Calais"},
  {title: "Catera", value: "Catera"},
  {title: "Cimarron", value: "Cimarron"},
  {title: "CTS", value: "CTS"},
  {title: "CTS Coupe", value: "CTS Coupe"},
  {title: "CTS Wagon", value: "CTS Wagon"},
  {title: "CTS-V", value: "CTS-V"},
  {title: "CTS-V Coupe", value: "CTS-V Coupe"},
  {title: "CTS-V Wagon", value: "CTS-V Wagon"},
  {title: "DeVille", value: "DeVille"},
  {title: "DTS", value: "DTS"},
  {title: "Eldorado", value: "Eldorado"},
  {title: "ELR", value: "ELR"},
  {title: "Escalade", value: "Escalade"},
  {title: "Escalade ESV", value: "Escalade ESV"},
  {title: "Fleetwood", value: "Fleetwood"},
  {title: "Imaj", value: "Imaj"},
  {title: "Le Mans", value: "Le Mans"},
  {title: "LMP", value: "LMP"},
  {title: "Park Avenue", value: "Park Avenue"},
  {title: "Seville", value: "Seville"},
  {title: "Sixty", value: "Sixty"},
  {title: "Solitaire", value: "Solitaire"},
  {title: "SRX", value: "SRX"},
  {title: "STS", value: "STS"},
  {title: "STS-V", value: "STS-V"},
  {title: "V Sixteen", value: "V Sixteen"},
  {title: "Vizon", value: "Vizon"},
  {title: "XLR", value: "XLR"},
  {title: "XTS ", value: "XTS "},
];

const chevrolet = [
  {title: "2103", value: "2103"},
  {title: "Adventure", value: "Adventure"},
  {title: "Aerovette", value: "Aerovette"},
  {title: "Alero", value: "Alero"},
  {title: "APV", value: "APV"},
  {title: "Astro", value: "Astro"},
  {title: "Astrovette", value: "Astrovette"},
  {title: "Avalanche", value: "Avalanche"},
  {title: "Aveo", value: "Aveo"},
  {title: "Bel Air", value: "Bel Air"},
  {title: "Beretta", value: "Beretta"},
  {title: "Biscayne", value: "Biscayne"},
  {title: "Blazer", value: "Blazer"},
  {title: "C-10", value: "C-10"},
  {title: "Camaro", value: "Camaro"},
  {title: "Caprice", value: "Caprice"},
  {title: "Captiva", value: "Captiva"},
  {title: "Cavalier", value: "Cavalier"},
  {title: "Celebrity", value: "Celebrity"},
  {title: "Celta", value: "Celta"},
  {title: "Chevelle", value: "Chevelle"},
  {title: "Chevette", value: "Chevette"},
  {title: "Cheyenne", value: "Cheyenne"},
  {title: "Citation", value: "Citation"},
  {title: "Citation II", value: "Citation II"},
  {title: "City Express", value: "City Express"},
  {title: "Cobalt", value: "Cobalt"},
  {title: "Colorado", value: "Colorado"},
  {title: "Comodoro", value: "Comodoro"},
  {title: "Corsica", value: "Corsica"},
  {title: "Corvair", value: "Corvair"},
  {title: "Corvette", value: "Corvette"},
  {title: "Corvette Stingray", value: "Corvette Stingray"},
  {title: "Cruze", value: "Cruze"},
  {title: "DeLuxe", value: "DeLuxe"},
  {title: "DeVille", value: "DeVille"},
  {title: "El Camino", value: "El Camino"},
  {title: "Epica", value: "Epica"},
  {title: "Equinox", value: "Equinox"},
  {title: "Evanda", value: "Evanda"},
  {title: "Express", value: "Express"},
  {title: "Express Cargo", value: "Express Cargo"},
  {title: "Grand Blazer", value: "Grand Blazer"},
  {title: "Half-Ton", value: "Half-Ton"},
  {title: "HHR", value: "HHR"},
  {title: "Impala", value: "Impala"},
  {title: "Intimidator", value: "Intimidator"},
  {title: "Journey", value: "Journey"},
  {title: "K-20", value: "K-20"},
  {title: "Kalos", value: "Kalos"},
  {title: "Kodiak", value: "Kodiak"},
  {title: "Lacetti", value: "Lacetti"},
  {title: "Lumina", value: "Lumina"},
  {title: "Malibu", value: "Malibu"},
  {title: "Matiz", value: "Matiz"},
  {title: "Metro", value: "Metro"},
  {title: "Monte Carlo", value: "Monte Carlo"},
  {title: "Monza", value: "Monza"},
  {title: "Nomad", value: "Nomad"},
  {title: "Nova", value: "Nova"},
  {title: "Nubira", value: "Nubira"},
  {title: "Optra", value: "Optra"},
  {title: "Orlando", value: "Orlando"},
  {title: "Pickup", value: "Pickup"},
  {title: "Prizm", value: "Prizm"},
  {title: "Relsamo", value: "Relsamo"},
  {title: "Rezzo", value: "Rezzo"},
  {title: "S-10", value: "S-10"},
  {title: "Sabia", value: "Sabia"},
  {title: "Silverado", value: "Silverado"},
  {title: "Silverado 1500", value: "Silverado 1500"},
  {title: "Silverado 2500HD", value: "Silverado 2500HD"},
  {title: "Silverado 3500HD", value: "Silverado 3500HD"},
  {title: "Sonic", value: "Sonic"},
  {title: "Spark", value: "Spark"},
  {title: "Spark EV", value: "Spark EV"},
  {title: "Sprint", value: "Sprint"},
  {title: "SS", value: "SS"},
  {title: "SSR", value: "SSR"},
  {title: "Suburban", value: "Suburban"},
  {title: "Tahoe", value: "Tahoe"},
  {title: "Tandem 2000", value: "Tandem 2000"},
  {title: "Tracker", value: "Tracker"},
  {title: "Trailblazer", value: "Trailblazer"},
  {title: "Trans Sport", value: "Trans Sport"},
  {title: "Traverse", value: "Traverse"},
  {title: "Trax", value: "Trax"},
  {title: "Triax", value: "Triax"},
  {title: "Uplander", value: "Uplander"},
  {title: "Vega", value: "Vega"},
  {title: "Venture", value: "Venture"},
  {title: "Vivant", value: "Vivant"},
  {title: "Volt", value: "Volt"},
  {title: "XP 882", value: "XP 882"},
  {title: "XP 897 GT", value: "XP 897 GT"},
  {title: "XP 898", value: "XP 898"},
];

const citroen = [
  {title: "1.6", value: "1.6"},
  {title: "11", value: "11"},
  {title: "15", value: "15"},
  {title: "2CV", value: "2CV"},
  {title: "7", value: "7"},
  {title: "7A", value: "7A"},
  {title: "Activa", value: "Activa"},
  {title: "Ak 350", value: "Ak 350"},
  {title: "Ami", value: "Ami"},
  {title: "Aventure", value: "Aventure"},
  {title: "AX", value: "AX"},
  {title: "Axel", value: "Axel"},
  {title: "Berlingo", value: "Berlingo"},
  {title: "Bijou", value: "Bijou"},
  {title: "BX", value: "BX"},
  {title: "C", value: "C"},
  {title: "C 15", value: "C 15"},
  {title: "C-Airdream", value: "C-Airdream"},
  {title: "C-Crosser", value: "C-Crosser"},
  {title: "C-Zero", value: "C-Zero"},
  {title: "C1", value: "C1"},
  {title: "C2", value: "C2"},
  {title: "C3", value: "C3"},
  {title: "C4", value: "C4"},
  {title: "C5", value: "C5"},
  {title: "C6", value: "C6"},
  {title: "C8", value: "C8"},
  {title: "CX", value: "CX"},
  {title: "DS", value: "DS"},
  {title: "Dyane", value: "Dyane"},
  {title: "Dyane 4", value: "Dyane 4"},
  {title: "Dyane 6", value: "Dyane 6"},
  {title: "Eco 2000", value: "Eco 2000"},
  {title: "Eole", value: "Eole"},
  {title: "GS", value: "GS"},
  {title: "GSA", value: "GSA"},
  {title: "ID 19", value: "ID 19"},
  {title: "Karin", value: "Karin"},
  {title: "LN", value: "LN"},
  {title: "LNA", value: "LNA"},
  {title: "Mehari", value: "Mehari"},
  {title: "Mini-Zup", value: "Mini-Zup"},
  {title: "Multispace", value: "Multispace"},
  {title: "Osee", value: "Osee"},
  {title: "Picasso", value: "Picasso"},
  {title: "Pluriel", value: "Pluriel"},
  {title: "Rally Raid", value: "Rally Raid"},
  {title: "Saxo", value: "Saxo"},
  {title: "SM", value: "SM"},
  {title: "Traction", value: "Traction"},
  {title: "Visa", value: "Visa"},
  {title: "Xanae", value: "Xanae"},
  {title: "Xantia", value: "Xantia"},
  {title: "XM", value: "XM"},
  {title: "Xsara", value: "Xsara"},
  {title: "ZX", value: "ZX"},
];

const dodge = [
  {title: "600", value: "600"},
  {title: "Aspen", value: "Aspen"},
  {title: "Avenger", value: "Avenger"},
  {title: "Caliber", value: "Caliber"},
  {title: "Caravan", value: "Caravan"},
  {title: "Challenger", value: "Challenger"},
  {title: "Charger", value: "Charger"},
  {title: "Charger RT Concept", value: "Charger RT Concept"},
  {title: "Colt", value: "Colt"},
  {title: "Conquest", value: "Conquest"},
  {title: "Copperhead", value: "Copperhead"},
  {title: "Coronet", value: "Coronet"},
  {title: "Custom", value: "Custom"},
  {title: "Dakota", value: "Dakota"},
  {title: "Dart", value: "Dart"},
  {title: "Daytona", value: "Daytona"},
  {title: "Durango", value: "Durango"},
  {title: "Dynasty", value: "Dynasty"},
  {title: "Grand Caravan", value: "Grand Caravan"},
  {title: "Hemi Super 8", value: "Hemi Super 8"},
  {title: "Intrepid", value: "Intrepid"},
  {title: "Journey", value: "Journey"},
  {title: "Kahuna", value: "Kahuna"},
  {title: "Lancer", value: "Lancer"},
  {title: "M80", value: "M80"},
  {title: "Magnum", value: "Magnum"},
  {title: "Maxx Cab", value: "Maxx Cab"},
  {title: "Mirada", value: "Mirada"},
  {title: "Monaco", value: "Monaco"},
  {title: "Neon", value: "Neon"},
  {title: "Nitro", value: "Nitro"},
  {title: "Omni", value: "Omni"},
  {title: "Polara", value: "Polara"},
  {title: "Power Box", value: "Power Box"},
  {title: "Prowler", value: "Prowler"},
  {title: "Ram", value: "Ram"},
  {title: "Razor", value: "Razor"},
  {title: "Shadow", value: "Shadow"},
  {title: "Sidewinder", value: "Sidewinder"},
  {title: "Spirit", value: "Spirit"},
  {title: "Sprinter", value: "Sprinter"},
  {title: "SRT Viper", value: "SRT Viper"},
  {title: "Stealth", value: "Stealth"},
  {title: "Stratus", value: "Stratus"},
  {title: "T-Rex 6x6", value: "T-Rex 6x6"},
  {title: "Venom", value: "Venom"},
  {title: "Viper", value: "Viper"},
  {title: "WC 51", value: "WC 51"},
];

const ferrari = [
  {title: "125", value: "125"},
  {title: "125 F1", value: "125 F1"},
  {title: "125S", value: "125S"},
  {title: "126", value: "126"},
  {title: "156", value: "156"},
  {title: "158", value: "158"},
  {title: "159S", value: "159S"},
  {title: "166", value: "166"},
  {title: "195", value: "195"},
  {title: "196", value: "196"},
  {title: "206", value: "206"},
  {title: "208", value: "208"},
  {title: "212", value: "212"},
  {title: "225", value: "225"},
  {title: "246", value: "246"},
  {title: "250", value: "250"},
  {title: "250 GT", value: "250 GT"},
  {title: "250 GTE", value: "250 GTE"},
  {title: "250 GTO", value: "250 GTO"},
  {title: "250 LM", value: "250 LM"},
  {title: "250 Mille Miglia", value: "250 Mille Miglia"},
  {title: "250 Testarossa", value: "250 Testarossa"},
  {title: "255 S", value: "255 S"},
  {title: "256 F1", value: "256 F1"},
  {title: "275", value: "275"},
  {title: "288 GTO", value: "288 GTO"},
  {title: "306", value: "306"},
  {title: "308", value: "308"},
  {title: "312", value: "312"},
  {title: "328 GTB", value: "328 GTB"},
  {title: "328 GTS", value: "328 GTS"},
  {title: "330", value: "330"},
  {title: "330GT", value: "330GT"},
  {title: "340 America", value: "340 America"},
  {title: "340 F1", value: "340 F1"},
  {title: "340 Mexico", value: "340 Mexico"},
  {title: "340 MM", value: "340 MM"},
  {title: "340 Spider", value: "340 Spider"},
  {title: "342 America", value: "342 America"},
  {title: "348", value: "348"},
  {title: "348 TS Targa", value: "348 TS Targa"},
  {title: "355 Spider", value: "355 Spider"},
  {title: "355 TS", value: "355 TS"},
  {title: "360", value: "360"},
  {title: "365 BB", value: "365 BB"},
  {title: "365 California", value: "365 California"},
  {title: "365 GT", value: "365 GT"},
  {title: "365 GT4", value: "365 GT4"},
  {title: "365 GTB", value: "365 GTB"},
  {title: "365 GTC", value: "365 GTC"},
  {title: "365 GTC 4", value: "365 GTC 4"},
  {title: "365 GTS", value: "365 GTS"},
  {title: "375 America", value: "375 America"},
  {title: "375 Indy", value: "375 Indy"},
  {title: "375 Mille Miglia", value: "375 Mille Miglia"},
  {title: "3Z", value: "3Z"},
  {title: "400", value: "400"},
  {title: "400 Superamerica", value: "400 Superamerica"},
  {title: "410 Superamerica", value: "410 Superamerica"},
  {title: "412 GT", value: "412 GT"},
  {title: "412 MI", value: "412 MI"},
  {title: "412 T2", value: "412 T2"},
  {title: "456", value: "456"},
  {title: "456M", value: "456M"},
  {title: "458", value: "458"},
  {title: "458 Italia", value: "458 Italia"},
  {title: "500 F2", value: "500 F2"},
  {title: "500 Mondial", value: "500 Mondial"},
  {title: "500 Superfast", value: "500 Superfast"},
  {title: "500 Testarossa", value: "500 Testarossa"},
  {title: "512 BB", value: "512 BB"},
  {title: "512 BBi", value: "512 BBi"},
  {title: "512 BBi Turbo", value: "512 BBi Turbo"},
  {title: "512 F1", value: "512 F1"},
  {title: "512 M", value: "512 M"},
  {title: "512 S", value: "512 S"},
  {title: "512 TR", value: "512 TR"},
  {title: "550", value: "550"},
  {title: "553 F1", value: "553 F1"},
  {title: "553 F2", value: "553 F2"},
  {title: "575 Superamerica", value: "575 Superamerica"},
  {title: "575M Maranello", value: "575M Maranello"},
  {title: "599", value: "599"},
  {title: "599 GTB Fiorano", value: "599 GTB Fiorano"},
  {title: "612", value: "612"},
  {title: "612 Scaglietti", value: "612 Scaglietti"},
  {title: "625 F1", value: "625 F1"},
  {title: "735", value: "735"},
  {title: "750", value: "750"},
  {title: "801 F1", value: "801 F1"},
  {title: "850", value: "850"},
  {title: "C62", value: "C62"},
  {title: "California", value: "California"},
  {title: "D 50", value: "D 50"},
  {title: "Dino", value: "Dino"},
  {title: "Enzo", value: "Enzo"},
  {title: "F 2005", value: "F 2005"},
  {title: "F1 156", value: "F1 156"},
  {title: "F1 2000", value: "F1 2000"},
  {title: "F1 86", value: "F1 86"},
  {title: "F1 88", value: "F1 88"},
  {title: "F1 89", value: "F1 89"},
  {title: "F1 90", value: "F1 90"},
  {title: "F1 93", value: "F1 93"},
  {title: "F310", value: "F310"},
  {title: "F333", value: "F333"},
  {title: "F355", value: "F355"},
  {title: "F399", value: "F399"},
  {title: "F40", value: "F40"},
  {title: "F430", value: "F430"},
  {title: "F50", value: "F50"},
  {title: "F512 M", value: "F512 M"},
  {title: "F55", value: "F55"},
  {title: "F550", value: "F550"},
  {title: "FF", value: "FF"},
  {title: "FF HELE", value: "FF HELE"},
  {title: "GTO", value: "GTO"},
  {title: "KS 360 Modena", value: "KS 360 Modena"},
  {title: "Maranello", value: "Maranello"},
  {title: "Mondial", value: "Mondial"},
  {title: "Mythos", value: "Mythos"},
  {title: "P2", value: "P2"},
  {title: "P5", value: "P5"},
  {title: "Pinin", value: "Pinin"},
  {title: "Rossa", value: "Rossa"},
  {title: "Superamerica", value: "Superamerica"},
  {title: "Testarossa", value: "Testarossa"},
];

const ford = [
  {title: "021 C", value: "021 C"},
  {title: "12 M", value: "12 M"},
  {title: "17", value: "17"},
  {title: "17M", value: "17M"},
  {title: "2000", value: "2000"},
  {title: "24.7", value: "24.7"},
  {title: "427", value: "427"},
  {title: "49", value: "49"},
  {title: "Aerostar", value: "Aerostar"},
  {title: "Anglia", value: "Anglia"},
  {title: "Artic", value: "Artic"},
  {title: "Aspire", value: "Aspire"},
  {title: "Bantam", value: "Bantam"},
  {title: "Bronco", value: "Bronco"},
  {title: "Bronco II", value: "Bronco II"},
  {title: "C 100", value: "C 100"},
  {title: "C-MAX", value: "C-MAX"},
  {title: "C-Max Energi", value: "C-Max Energi"},
  {title: "C-Max Hybrid", value: "C-Max Hybrid"},
  {title: "Capri", value: "Capri"},
  {title: "Coin", value: "Coin"},
  {title: "Consul", value: "Consul"},
  {title: "Contour", value: "Contour"},
  {title: "Corsair", value: "Corsair"},
  {title: "Cortina", value: "Cortina"},
  {title: "Cougar", value: "Cougar"},
  {title: "Courier", value: "Courier"},
  {title: "Crestline", value: "Crestline"},
  {title: "Crown Victoria", value: "Crown Victoria"},
  {title: "Custom", value: "Custom"},
  {title: "Desert Excursion", value: "Desert Excursion"},
  {title: "E-150", value: "E-150"},
  {title: "E-250", value: "E-250"},
  {title: "E-350", value: "E-350"},
  {title: "e-Ka", value: "e-Ka"},
  {title: "E-Series", value: "E-Series"},
  {title: "E-Series Van", value: "E-Series Van"},
  {title: "E-Series Wagon", value: "E-Series Wagon"},
  {title: "Econoline", value: "Econoline"},
  {title: "Econovan", value: "Econovan"},
  {title: "Ecosport", value: "Ecosport"},
  {title: "Edge", value: "Edge"},
  {title: "Equator", value: "Equator"},
  {title: "Escape", value: "Escape"},
  {title: "Escort", value: "Escort"},
  {title: "EX", value: "EX"},
  {title: "Excursion", value: "Excursion"},
  {title: "Expedition", value: "Expedition"},
  {title: "Explorer", value: "Explorer"},
  {title: "Extreme EX", value: "Extreme EX"},
  {title: "F", value: "F"},
  {title: "F-150", value: "F-150"},
  {title: "F-250", value: "F-250"},
  {title: "F-250 Super Duty", value: "F-250 Super Duty"},
  {title: "F-350", value: "F-350"},
  {title: "F-350 Super Duty", value: "F-350 Super Duty"},
  {title: "F-450", value: "F-450"},
  {title: "F-450 Super Duty", value: "F-450 Super Duty"},
  {title: "F-650", value: "F-650"},
  {title: "Fairlane", value: "Fairlane"},
  {title: "Falcon", value: "Falcon"},
  {title: "Festiva", value: "Festiva"},
  {title: "Fiesta", value: "Fiesta"},
  {title: "Five Hundred", value: "Five Hundred"},
  {title: "Flex", value: "Flex"},
  {title: "Focus", value: "Focus"},
  {title: "Focus ST", value: "Focus ST"},
  {title: "FPV BF GT", value: "FPV BF GT"},
  {title: "Freestar", value: "Freestar"},
  {title: "Freestyle", value: "Freestyle"},
  {title: "Fusion", value: "Fusion"},
  {title: "Fusion Energi", value: "Fusion Energi"},
  {title: "Fusion Hybrid", value: "Fusion Hybrid"},
  {title: "Galaxie", value: "Galaxie"},
  {title: "Galaxy", value: "Galaxy"},
  {title: "Gran Torino", value: "Gran Torino"},
  {title: "Granada", value: "Granada"},
  {title: "GT", value: "GT"},
  {title: "GT 40", value: "GT 40"},
  {title: "GT 500", value: "GT 500"},
  {title: "GT 70", value: "GT 70"},
  {title: "Husky", value: "Husky"},
  {title: "Ikon", value: "Ikon"},
  {title: "Indigo", value: "Indigo"},
  {title: "Ka", value: "Ka"},
  {title: "Kuga", value: "Kuga"},
  {title: "Laser", value: "Laser"},
  {title: "Libre", value: "Libre"},
  {title: "Limited", value: "Limited"},
  {title: "Lotus Cortina", value: "Lotus Cortina"},
  {title: "LTD", value: "LTD"},
  {title: "Lynx", value: "Lynx"},
  {title: "Maverick", value: "Maverick"},
  {title: "Megastar II", value: "Megastar II"},
  {title: "Meteor", value: "Meteor"},
  {title: "Model U", value: "Model U"},
  {title: "Monarch", value: "Monarch"},
  {title: "Mondeo", value: "Mondeo"},
  {title: "Mustang", value: "Mustang"},
  {title: "O21 C", value: "O21 C"},
  {title: "Orion", value: "Orion"},
  {title: "Pilot", value: "Pilot"},
  {title: "Popular", value: "Popular"},
  {title: "Prefect", value: "Prefect"},
  {title: "Probe", value: "Probe"},
  {title: "Puma", value: "Puma"},
  {title: "Ranchero", value: "Ranchero"},
  {title: "Ranger", value: "Ranger"},
  {title: "Royale", value: "Royale"},
  {title: "RS 200", value: "RS 200"},
  {title: "S-Max", value: "S-Max"},
  {title: "Saetta", value: "Saetta"},
  {title: "Scorpio", value: "Scorpio"},
  {title: "Shelby GR-1 Concept", value: "Shelby GR-1 Concept"},
  {title: "Shelby GT 500", value: "Shelby GT 500"},
  {title: "Shelby GT500", value: "Shelby GT500"},
  {title: "Sierra", value: "Sierra"},
  {title: "Skyliner", value: "Skyliner"},
  {title: "ST 460", value: "ST 460"},
  {title: "Station Wagon", value: "Station Wagon"},
  {title: "Synergy 2010", value: "Synergy 2010"},
  {title: "Taunus", value: "Taunus"},
  {title: "Taurus", value: "Taurus"},
  {title: "Taurus X", value: "Taurus X"},
  {title: "TE-50", value: "TE-50"},
  {title: "Telstar", value: "Telstar"},
  {title: "Tempo", value: "Tempo"},
  {title: "Territory", value: "Territory"},
  {title: "Think", value: "Think"},
  {title: "Think Neighbor", value: "Think Neighbor"},
  {title: "Thunderbird", value: "Thunderbird"},
  {title: "TL-50", value: "TL-50"},
  {title: "Tonka", value: "Tonka"},
  {title: "Torino", value: "Torino"},
  {title: "Tracer", value: "Tracer"},
  {title: "Transit Connect", value: "Transit Connect"},
  {title: "Transit Van", value: "Transit Van"},
  {title: "Transit Wagon", value: "Transit Wagon"},
  {title: "Triton", value: "Triton"},
  {title: "TS-50", value: "TS-50"},
  {title: "Urban Explorer", value: "Urban Explorer"},
  {title: "Vedette", value: "Vedette"},
  {title: "Versailles", value: "Versailles"},
  {title: "Windstar", value: "Windstar"},
  {title: "XR 8 Xplod", value: "XR 8 Xplod"},
  {title: "Zephyr", value: "Zephyr"},
  {title: "Zodiac", value: "Zodiac"},
];

const GMC = [
  {title: "Acadia", value: "Acadia"},
  {title: "Autonomy", value: "Autonomy"},
  {title: "Canyon", value: "Canyon"},
  {title: "Envoy", value: "Envoy"},
  {title: "EV1", value: "EV1"},
  {title: "Firebird", value: "Firebird"},
  {title: "Jimmy", value: "Jimmy"},
  {title: "Safari", value: "Safari"},
  {title: "Savana", value: "Savana"},
  {title: "Sierra", value: "Sierra"},
  {title: "Sierra 1500", value: "Sierra 1500"},
  {title: "Sierra 2500HD", value: "Sierra 2500HD"},
  {title: "Sierra 3500HD", value: "Sierra 3500HD"},
  {title: "Sonoma", value: "Sonoma"},
  {title: "Suburban", value: "Suburban"},
  {title: "Terra 4", value: "Terra 4"},
  {title: "Terracross", value: "Terracross"},
  {title: "Terradyne", value: "Terradyne"},
  {title: "Terrain", value: "Terrain"},
  {title: "Typhoon", value: "Typhoon"},
  {title: "Yukon", value: "Yukon"},
  {title: "Yukon XL", value: "Yukon XL"},
];

const honda = [
  {title: "1300", value: "1300"},
  {title: "145", value: "145"},
  {title: "Accord", value: "Accord"},
  {title: "Accord Crosstour", value: "Accord Crosstour"},
  {title: "Accord Hybrid", value: "Accord Hybrid"},
  {title: "Accord Plug-In Hybrid", value: "Accord Plug-In Hybrid"},
  {title: "Acty", value: "Acty"},
  {title: "Argento Viva", value: "Argento Viva"},
  {title: "Avancier", value: "Avancier"},
  {title: "Ballade", value: "Ballade"},
  {title: "Capa", value: "Capa"},
  {title: "City", value: "City"},
  {title: "Civic", value: "Civic"},
  {title: "Civic Del Sol", value: "Civic Del Sol"},
  {title: "Concerto", value: "Concerto"},
  {title: "CR-V", value: "CR-V"},
  {title: "CR-Z", value: "CR-Z"},
  {title: "Crosstour", value: "Crosstour"},
  {title: "CRX", value: "CRX"},
  {title: "Element", value: "Element"},
  {title: "EV", value: "EV"},
  {title: "F1", value: "F1"},
  {title: "FCX", value: "FCX"},
  {title: "Fit", value: "Fit"},
  {title: "FR-V", value: "FR-V"},
  {title: "Fuya Jo", value: "Fuya Jo"},
  {title: "HP-X", value: "HP-X"},
  {title: "HR-V", value: "HR-V"},
  {title: "Insight", value: "Insight"},
  {title: "Inspire", value: "Inspire"},
  {title: "Integra", value: "Integra"},
  {title: "J-VX", value: "J-VX"},
  {title: "Jazz", value: "Jazz"},
  {title: "Lagreat", value: "Lagreat"},
  {title: "Legend", value: "Legend"},
  {title: "Life", value: "Life"},
  {title: "Logo", value: "Logo"},
  {title: "Mobilio", value: "Mobilio"},
  {title: "Model X", value: "Model X"},
  {title: "N III", value: "N III"},
  {title: "NSX", value: "NSX"},
  {title: "Odyssey", value: "Odyssey"},
  {title: "Passport", value: "Passport"},
  {title: "Pilot", value: "Pilot"},
  {title: "Prelude", value: "Prelude"},
  {title: "Quintet", value: "Quintet"},
  {title: "Ridgeline", value: "Ridgeline"},
  {title: "S-MX", value: "S-MX"},
  {title: "S2000", value: "S2000"},
  {title: "S500", value: "S500"},
  {title: "S600", value: "S600"},
  {title: "S800", value: "S800"},
  {title: "Saber", value: "Saber"},
  {title: "Shuttle", value: "Shuttle"},
  {title: "SSM", value: "SSM"},
  {title: "Step Wagon", value: "Step Wagon"},
  {title: "Stream", value: "Stream"},
  {title: "That", value: "That"},
  {title: "Today", value: "Today"},
  {title: "Torneo", value: "Torneo"},
  {title: "Vamos", value: "Vamos"},
  {title: "Z", value: "Z"},
];

const hyundai = [
  {title: "Accent", value: "Accent"},
  {title: "Atos", value: "Atos"},
  {title: "Azera", value: "Azera"},
  {title: "Clix", value: "Clix"},
  {title: "Coupe", value: "Coupe"},
  {title: "Dynasty", value: "Dynasty"},
  {title: "Elantra", value: "Elantra"},
  {title: "Elantra GT", value: "Elantra GT"},
  {title: "Entourage", value: "Entourage"},
  {title: "Equus", value: "Equus"},
  {title: "Euro 1", value: "Euro 1"},
  {title: "Excel", value: "Excel"},
  {title: "Galloper", value: "Galloper"},
  {title: "Genesis", value: "Genesis"},
  {title: "Genesis Coupe", value: "Genesis Coupe"},
  {title: "Getz", value: "Getz"},
  {title: "Grandeur", value: "Grandeur"},
  {title: "H1", value: "H1"},
  {title: "H100", value: "H100"},
  {title: "HCD-7", value: "HCD-7"},
  {title: "HCD-III", value: "HCD-III"},
  {title: "HED-5", value: "HED-5"},
  {title: "HED-6", value: "HED-6"},
  {title: "i10", value: "i10"},
  {title: "i20", value: "i20"},
  {title: "i30", value: "i30"},
  {title: "i40", value: "i40"},
  {title: "ix20", value: "ix20"},
  {title: "ix35", value: "ix35"},
  {title: "Lantra", value: "Lantra"},
  {title: "Marcia", value: "Marcia"},
  {title: "Matrix", value: "Matrix"},
  {title: "Neos", value: "Neos"},
  {title: "Panel Van", value: "Panel Van"},
  {title: "Pony", value: "Pony"},
  {title: "Portico", value: "Portico"},
  {title: "Santa Fe", value: "Santa Fe"},
  {title: "Santa Fe Sport", value: "Santa Fe Sport"},
  {title: "Satellite", value: "Satellite"},
  {title: "Scoupe", value: "Scoupe"},
  {title: "Sonata", value: "Sonata"},
  {title: "Sonata Hybrid", value: "Sonata Hybrid"},
  {title: "Stellar", value: "Stellar"},
  {title: "Terracan", value: "Terracan"},
  {title: "Tiburon", value: "Tiburon"},
  {title: "Tipper", value: "Tipper"},
  {title: "Trajet", value: "Trajet"},
  {title: "Tucson", value: "Tucson"},
  {title: "Veloster", value: "Veloster"},
  {title: "Veracruz", value: "Veracruz"},
  {title: "XG", value: "XG"},
  {title: "XG 300", value: "XG 300"},
  {title: "XG 350", value: "XG 350"},
];

const jaguar = [
  {title: "220", value: "220"},
  {title: "240", value: "240"},
  {title: "3.8", value: "3.8"},
  {title: "420G", value: "420G"},
  {title: "C-Type", value: "C-Type"},
  {title: "Concept Eight", value: "Concept Eight"},
  {title: "E Type", value: "E Type"},
  {title: "E-Type", value: "E-Type"},
  {title: "F-Type", value: "F-Type"},
  {title: "Kensington", value: "Kensington"},
  {title: "Mark IV", value: "Mark IV"},
  {title: "MK 10", value: "MK 10"},
  {title: "MK II", value: "MK II"},
  {title: "MK IV", value: "MK IV"},
  {title: "MK IX", value: "MK IX"},
  {title: "MK V", value: "MK V"},
  {title: "MK VII", value: "MK VII"},
  {title: "MK VIII", value: "MK VIII"},
  {title: "MK X", value: "MK X"},
  {title: "R Coupe", value: "R Coupe"},
  {title: "R-D6", value: "R-D6"},
  {title: "S-Type", value: "S-Type"},
  {title: "Sovereign", value: "Sovereign"},
  {title: "SS", value: "SS"},
  {title: "Type E", value: "Type E"},
  {title: "Type S", value: "Type S"},
  {title: "Type-C", value: "Type-C"},
  {title: "Vanden Plas", value: "Vanden Plas"},
  {title: "X-300", value: "X-300"},
  {title: "X-Type", value: "X-Type"},
  {title: "X400", value: "X400"},
  {title: "XF", value: "XF"},
  {title: "XJ", value: "XJ"},
  {title: "XJ-13", value: "XJ-13"},
  {title: "XJ220", value: "XJ220"},
  {title: "XJ6", value: "XJ6"},
  {title: "XJ8", value: "XJ8"},
  {title: "XJR", value: "XJR"},
  {title: "XJR-11", value: "XJR-11"},
  {title: "XJR-15", value: "XJR-15"},
  {title: "XJS", value: "XJS"},
  {title: "XK", value: "XK"},
  {title: "XK8", value: "XK8"},
  {title: "XKA", value: "XKA"},
  {title: "XKR", value: "XKR"},
  {title: "XS", value: "XS"},
];

const jeep = [
  {title: "Cherokee", value: "Cherokee"},
  {title: "CJ", value: "CJ"},
  {title: "CJ2", value: "CJ2"},
  {title: "CJ2A", value: "CJ2A"},
  {title: "CJ3A", value: "CJ3A"},
  {title: "CJ5", value: "CJ5"},
  {title: "CJ7", value: "CJ7"},
  {title: "Commander", value: "Commander"},
  {title: "Compass", value: "Compass"},
  {title: "Dakar", value: "Dakar"},
  {title: "Grand Cherokee", value: "Grand Cherokee"},
  {title: "Grand Cherokee SRT", value: "Grand Cherokee SRT"},
  {title: "Grand Wagoneer", value: "Grand Wagoneer"},
  {title: "Icon", value: "Icon"},
  {title: "Jeepster", value: "Jeepster"},
  {title: "Liberty", value: "Liberty"},
  {title: "MB", value: "MB"},
  {title: "Patriot", value: "Patriot"},
  {title: "Renegade", value: "Renegade"},
  {title: "Station Wagon", value: "Station Wagon"},
  {title: "Varsity", value: "Varsity"},
  {title: "Willys", value: "Willys"},
  {title: "Willys 2", value: "Willys 2"},
  {title: "Wrangler", value: "Wrangler"},
];

const kia = [
  {title: "Amanti", value: "Amanti"},
  {title: "Avella", value: "Avella"},
  {title: "Borrego", value: "Borrego"},
  {title: "Brisa", value: "Brisa"},
  {title: "Cadenza", value: "Cadenza"},
  {title: "Capital", value: "Capital"},
  {title: "Carens", value: "Carens"},
  {title: "Carnival", value: "Carnival"},
  {title: "Cee'd", value: "Cee'd"},
  {title: "Cerato", value: "Cerato"},
  {title: "Clarus", value: "Clarus"},
  {title: "Elan", value: "Elan"},
  {title: "Forte", value: "Forte"},
  {title: "Joice", value: "Joice"},
  {title: "K2700", value: "K2700"},
  {title: "K900", value: "K900"},
  {title: "KCV-4", value: "KCV-4"},
  {title: "Magentis", value: "Magentis"},
  {title: "Opirus", value: "Opirus"},
  {title: "Optima", value: "Optima"},
  {title: "Optima Hybrid", value: "Optima Hybrid"},
  {title: "Picanto", value: "Picanto"},
  {title: "Potentia", value: "Potentia"},
  {title: "Pregio", value: "Pregio"},
  {title: "Pride Wagon", value: "Pride Wagon"},
  {title: "Pro-ceed", value: "Pro-ceed"},
  {title: "Retona", value: "Retona"},
  {title: "Rio", value: "Rio"},
  {title: "Rondo", value: "Rondo"},
  {title: "Sedona", value: "Sedona"},
  {title: "Sephia", value: "Sephia"},
  {title: "Sephia II", value: "Sephia II"},
  {title: "Shuma", value: "Shuma"},
  {title: "Shuma II", value: "Shuma II"},
  {title: "Sorento", value: "Sorento"},
  {title: "Soul", value: "Soul"},
  {title: "Soul EV", value: "Soul EV"},
  {title: "Spectra", value: "Spectra"},
  {title: "Spectra5", value: "Spectra5"},
  {title: "Sportage", value: "Sportage"},
  {title: "Towner", value: "Towner"},
  {title: "Venga", value: "Venga"},
  {title: "Visto", value: "Visto"},
  {title: "Xedos", value: "Xedos"},
];

const lexus = [
  {title: "CT", value: "CT"},
  {title: "CT 200h", value: "CT 200h"},
  {title: "Daytona", value: "Daytona"},
  {title: "ES", value: "ES"},
  {title: "ES 300h", value: "ES 300h"},
  {title: "ES 350", value: "ES 350"},
  {title: "FLV", value: "FLV"},
  {title: "GS", value: "GS"},
  {title: "GS 350", value: "GS 350"},
  {title: "GS 450h", value: "GS 450h"},
  {title: "GX", value: "GX"},
  {title: "GX 460", value: "GX 460"},
  {title: "HS", value: "HS"},
  {title: "IS", value: "IS"},
  {title: "IS 250", value: "IS 250"},
  {title: "IS 250 C", value: "IS 250 C"},
  {title: "IS 350", value: "IS 350"},
  {title: "IS 350 C", value: "IS 350 C"},
  {title: "IS F", value: "IS F"},
  {title: "LF-C", value: "LF-C"},
  {title: "LFA", value: "LFA"},
  {title: "LS", value: "LS"},
  {title: "LS 460", value: "LS 460"},
  {title: "LS 600h L", value: "LS 600h L"},
  {title: "LX", value: "LX"},
  {title: "LX 570", value: "LX 570"},
  {title: "Minority Report", value: "Minority Report"},
  {title: "NX 200t", value: "NX 200t"},
  {title: "NX 300h", value: "NX 300h"},
  {title: "RC 350", value: "RC 350"},
  {title: "RC F", value: "RC F"},
  {title: "RX", value: "RX"},
  {title: "RX 350", value: "RX 350"},
  {title: "RX 450h", value: "RX 450h"},
  {title: "SC", value: "SC"},
];

const lincoln = [
  {title: "Aviator", value: "Aviator"},
  {title: "Blackwood", value: "Blackwood"},
  {title: "Capri", value: "Capri"},
  {title: "Continental", value: "Continental"},
  {title: "LS", value: "LS"},
  {title: "Mark 7", value: "Mark 7"},
  {title: "Mark LT", value: "Mark LT"},
  {title: "Mark VI", value: "Mark VI"},
  {title: "Mark VII", value: "Mark VII"},
  {title: "Mark VIII", value: "Mark VIII"},
  {title: "Mark X", value: "Mark X"},
  {title: "MK 9", value: "MK 9"},
  {title: "MKC", value: "MKC"},
  {title: "MKS", value: "MKS"},
  {title: "MKT", value: "MKT"},
  {title: "MKX", value: "MKX"},
  {title: "MKZ", value: "MKZ"},
  {title: "Navigator", value: "Navigator"},
  {title: "Premiere", value: "Premiere"},
  {title: "Sentinel", value: "Sentinel"},
  {title: "Town Car", value: "Town Car"},
  {title: "Zephyr", value: "Zephyr"},
];

const mazda = [
  {title: "1000", value: "1000"},
  {title: "110 S", value: "110 S"},
  {title: "121", value: "121"},
  {title: "2", value: "2"},
  {title: "3", value: "3"},
  {title: "323", value: "323"},
  {title: "5", value: "5"},
  {title: "6", value: "6"},
  {title: "616", value: "616"},
  {title: "626", value: "626"},
  {title: "787", value: "787"},
  {title: "818", value: "818"},
  {title: "929", value: "929"},
  {title: "Activehicle", value: "Activehicle"},
  {title: "Atenza", value: "Atenza"},
  {title: "AZ", value: "AZ"},
  {title: "AZ-1", value: "AZ-1"},
  {title: "B2300", value: "B2300"},
  {title: "B2500", value: "B2500"},
  {title: "B3000", value: "B3000"},
  {title: "B4000", value: "B4000"},
  {title: "Brown Collection Verisa", value: "Brown Collection Verisa"},
  {title: "BT-50", value: "BT-50"},
  {title: "Carol", value: "Carol"},
  {title: "Chante", value: "Chante"},
  {title: "Cosmo", value: "Cosmo"},
  {title: "CU-X", value: "CU-X"},
  {title: "CX-05", value: "CX-05"},
  {title: "CX-09", value: "CX-09"},
  {title: "CX-5", value: "CX-5"},
  {title: "CX-7", value: "CX-7"},
  {title: "CX-9", value: "CX-9"},
  {title: "Demio", value: "Demio"},
  {title: "Drifter", value: "Drifter"},
  {title: "DrifterX", value: "DrifterX"},
  {title: "Etude", value: "Etude"},
  {title: "Eunos", value: "Eunos"},
  {title: "Familia", value: "Familia"},
  {title: "Kusabi", value: "Kusabi"},
  {title: "Lantis", value: "Lantis"},
  {title: "Laputa", value: "Laputa"},
  {title: "Levante", value: "Levante"},
  {title: "Luce", value: "Luce"},
  {title: "Marathon", value: "Marathon"},
  {title: "MAZDA2", value: "MAZDA2"},
  {title: "MAZDA3", value: "MAZDA3"},
  {title: "Mazda5", value: "Mazda5"},
  {title: "MAZDA6", value: "MAZDA6"},
  {title: "MazdaSpeed3", value: "MazdaSpeed3"},
  {title: "MazdaSpeed6", value: "MazdaSpeed6"},
  {title: "Midge", value: "Midge"},
  {title: "Millenia", value: "Millenia"},
  {title: "Montrose", value: "Montrose"},
  {title: "MPV", value: "MPV"},
  {title: "MS-6", value: "MS-6"},
  {title: "MS-8", value: "MS-8"},
  {title: "MS-9", value: "MS-9"},
  {title: "MX", value: "MX"},
  {title: "MX-3", value: "MX-3"},
  {title: "MX-5 Miata", value: "MX-5 Miata"},
  {title: "MX-6", value: "MX-6"},
  {title: "MX-Flexa", value: "MX-Flexa"},
  {title: "Persona", value: "Persona"},
  {title: "Premacy", value: "Premacy"},
  {title: "Protege", value: "Protege"},
  {title: "R 360", value: "R 360"},
  {title: "R-100", value: "R-100"},
  {title: "Roadster", value: "Roadster"},
  {title: "Rustler", value: "Rustler"},
  {title: "RX 4 Coupe", value: "RX 4 Coupe"},
  {title: "RX Evolv", value: "RX Evolv"},
  {title: "RX-01", value: "RX-01"},
  {title: "RX-2", value: "RX-2"},
  {title: "RX-3", value: "RX-3"},
  {title: "RX-4", value: "RX-4"},
  {title: "RX-7", value: "RX-7"},
  {title: "RX-8", value: "RX-8"},
  {title: "RX-Evolv", value: "RX-Evolv"},
  {title: "Sentia", value: "Sentia"},
  {title: "SPEED3", value: "SPEED3"},
  {title: "Spiano", value: "Spiano"},
  {title: "Sport Wagon", value: "Sport Wagon"},
  {title: "SW-X", value: "SW-X"},
  {title: "Tribute", value: "Tribute"},
  {title: "Washu", value: "Washu"},
  {title: "Xedos 9", value: "Xedos 9"},
];

const mercedes = [
  {title: "170 V", value: "170 V"},
  {title: "170S", value: "170S"},
  {title: "180", value: "180"},
  {title: "190", value: "190"},
  {title: "200", value: "200"},
  {title: "219", value: "219"},
  {title: "220", value: "220"},
  {title: "230", value: "230"},
  {title: "230.4", value: "230.4"},
  {title: "240", value: "240"},
  {title: "250", value: "250"},
  {title: "260", value: "260"},
  {title: "280", value: "280"},
  {title: "300", value: "300"},
  {title: "300B", value: "300B"},
  {title: "300D", value: "300D"},
  {title: "300S", value: "300S"},
  {title: "320", value: "320"},
  {title: "350", value: "350"},
  {title: "380", value: "380"},
  {title: "400", value: "400"},
  {title: "420", value: "420"},
  {title: "450", value: "450"},
  {title: "500", value: "500"},
  {title: "560", value: "560"},
  {title: "600", value: "600"},
  {title: "770", value: "770"},
  {title: "A", value: "A"},
  {title: "B", value: "B"},
  {title: "Bionic Car Concept", value: "Bionic Car Concept"},
  {title: "C", value: "C"},
  {title: "C 111", value: "C 111"},
  {title: "C 112", value: "C 112"},
  {title: "C-Class", value: "C-Class"},
  {title: "C30", value: "C30"},
  {title: "CK", value: "CK"},
  {title: "CL", value: "CL"},
  {title: "CL-Class", value: "CL-Class"},
  {title: "CLA-Class", value: "CLA-Class"},
  {title: "CLC", value: "CLC"},
  {title: "CLK", value: "CLK"},
  {title: "CLK GTR", value: "CLK GTR"},
  {title: "CLK LM", value: "CLK LM"},
  {title: "CLS", value: "CLS"},
  {title: "CLS-Class", value: "CLS-Class"},
  {title: "CW", value: "CW"},
  {title: "E", value: "E"},
  {title: "E-Class", value: "E-Class"},
  {title: "E420", value: "E420"},
  {title: "E500", value: "E500"},
  {title: "F200", value: "F200"},
  {title: "F300 Life Jet", value: "F300 Life Jet"},
  {title: "G", value: "G"},
  {title: "G-Class", value: "G-Class"},
  {title: "GL", value: "GL"},
  {title: "GL-Class", value: "GL-Class"},
  {title: "GLA-Class", value: "GLA-Class"},
  {title: "GLK", value: "GLK"},
  {title: "GLK-Class", value: "GLK-Class"},
  {title: "M", value: "M"},
  {title: "M-Class", value: "M-Class"},
  {title: "MCC", value: "MCC"},
  {title: "ML", value: "ML"},
  {title: "Ponton", value: "Ponton"},
  {title: "R", value: "R"},
  {title: "S", value: "S"},
  {title: "S-Class", value: "S-Class"},
  {title: "SC", value: "SC"},
  {title: "SE", value: "SE"},
  {title: "SL", value: "SL"},
  {title: "SL-Class", value: "SL-Class"},
  {title: "SLK", value: "SLK"},
  {title: "SLK-Class", value: "SLK-Class"},
  {title: "SLR McLaren", value: "SLR McLaren"},
  {title: "SLS", value: "SLS"},
  {title: "SLS AMG GT", value: "SLS AMG GT"},
  {title: "SLS AMG GT Final Edition", value: "SLS AMG GT Final Edition"},
  {title: "Smart", value: "Smart"},
  {title: "Sprinter", value: "Sprinter"},
  {title: "Studie", value: "Studie"},
  {title: "Swatch", value: "Swatch"},
  {title: "T", value: "T"},
  {title: "T V-12", value: "T V-12"},
  {title: "V", value: "V"},
  {title: "Vaneo", value: "Vaneo"},
  {title: "Version Longue", value: "Version Longue"},
  {title: "Viano", value: "Viano"},
  {title: "Vision", value: "Vision"},
  {title: "Vito", value: "Vito"},
  {title: "W 110", value: "W 110"},
  {title: "W 111", value: "W 111"},
  {title: "W 123 Coupe", value: "W 123 Coupe"},
  {title: "W 136", value: "W 136"},
  {title: "W 196", value: "W 196"},
];

const mitsubishi = [
  {title: "3000GT", value: "3000GT"},
  {title: "500", value: "500"},
  {title: "A10", value: "A10"},
  {title: "ASX", value: "ASX"},
  {title: "Carisma", value: "Carisma"},
  {title: "Celeste", value: "Celeste"},
  {title: "Challenger", value: "Challenger"},
  {title: "Colt", value: "Colt"},
  {title: "Debonair", value: "Debonair"},
  {title: "Delica Space Gear", value: "Delica Space Gear"},
  {title: "Diamante", value: "Diamante"},
  {title: "Dingo", value: "Dingo"},
  {title: "Dion", value: "Dion"},
  {title: "Eclipse", value: "Eclipse"},
  {title: "eK", value: "eK"},
  {title: "Endeavor", value: "Endeavor"},
  {title: "Field Guard", value: "Field Guard"},
  {title: "FTO", value: "FTO"},
  {title: "Galant", value: "Galant"},
  {title: "Gaus", value: "Gaus"},
  {title: "Grandis", value: "Grandis"},
  {title: "GTO", value: "GTO"},
  {title: "HSR-V", value: "HSR-V"},
  {title: "i-MiEV", value: "i-MiEV"},
  {title: "Jeep", value: "Jeep"},
  {title: "L 200", value: "L 200"},
  {title: "Lancer", value: "Lancer"},
  {title: "Lancer Evolution", value: "Lancer Evolution"},
  {title: "Lancer Sportback", value: "Lancer Sportback"},
  {title: "Magna", value: "Magna"},
  {title: "Minica", value: "Minica"},
  {title: "Mirage", value: "Mirage"},
  {title: "Montero", value: "Montero"},
  {title: "Mum 500", value: "Mum 500"},
  {title: "Nessie", value: "Nessie"},
  {title: "Outlander", value: "Outlander"},
  {title: "Outlander Sport", value: "Outlander Sport"},
  {title: "Pajero", value: "Pajero"},
  {title: "Proudia", value: "Proudia"},
  {title: "Raider", value: "Raider"},
  {title: "RPM 7000", value: "RPM 7000"},
  {title: "RVR", value: "RVR"},
  {title: "Sapporo", value: "Sapporo"},
  {title: "Shogun", value: "Shogun"},
  {title: "Shogun Pinin", value: "Shogun Pinin"},
  {title: "Sigma", value: "Sigma"},
  {title: "Space Liner", value: "Space Liner"},
  {title: "Space Runner", value: "Space Runner"},
  {title: "Space Star", value: "Space Star"},
  {title: "Space Wagon", value: "Space Wagon"},
  {title: "SSS", value: "SSS"},
  {title: "SST", value: "SST"},
  {title: "SSU", value: "SSU"},
  {title: "Starion", value: "Starion"},
  {title: "SUP", value: "SUP"},
  {title: "SUW", value: "SUW"},
  {title: "Valley", value: "Valley"},
  {title: "Verada", value: "Verada"},
];

const nissan = [
  {title: "100 NX", value: "100 NX"},
  {title: "110", value: "110"},
  {title: "1400", value: "1400"},
  {title: "200 SX Silvia", value: "200 SX Silvia"},
  {title: "211", value: "211"},
  {title: "240 C", value: "240 C"},
  {title: "260 ZX", value: "260 ZX"},
  {title: "270 R", value: "270 R"},
  {title: "300 ZX", value: "300 ZX"},
  {title: "350Z", value: "350Z"},
  {title: "370Z", value: "370Z"},
  {title: "400 R", value: "400 R"},
  {title: "AA-X", value: "AA-X"},
  {title: "Almera", value: "Almera"},
  {title: "Alpha", value: "Alpha"},
  {title: "Altima", value: "Altima"},
  {title: "Armada", value: "Armada"},
  {title: "Avenir", value: "Avenir"},
  {title: "AXY", value: "AXY"},
  {title: "AZ-1", value: "AZ-1"},
  {title: "Bluebird", value: "Bluebird"},
  {title: "C 52", value: "C 52"},
  {title: "Cedric", value: "Cedric"},
  {title: "Cefiro", value: "Cefiro"},
  {title: "Chappo", value: "Chappo"},
  {title: "Cherry", value: "Cherry"},
  {title: "Cima", value: "Cima"},
  {title: "Commercial", value: "Commercial"},
  {title: "CQ-X", value: "CQ-X"},
  {title: "Crew", value: "Crew"},
  {title: "Cube", value: "Cube"},
  {title: "DS-2", value: "DS-2"},
  {title: "E20", value: "E20"},
  {title: "El Grand", value: "El Grand"},
  {title: "Fairlady", value: "Fairlady"},
  {title: "Frontier", value: "Frontier"},
  {title: "Fusion", value: "Fusion"},
  {title: "Gloria", value: "Gloria"},
  {title: "Grand Livina", value: "Grand Livina"},
  {title: "GT-R", value: "GT-R"},
  {title: "Hardbody", value: "Hardbody"},
  {title: "HyperMini", value: "HyperMini"},
  {title: "Ideo", value: "Ideo"},
  {title: "Interstar", value: "Interstar"},
  {title: "Juke", value: "Juke"},
  {title: "Lafesta", value: "Lafesta"},
  {title: "Laurel", value: "Laurel"},
  {title: "Leaf", value: "Leaf"},
  {title: "Leopard", value: "Leopard"},
  {title: "Livina", value: "Livina"},
  {title: "M", value: "M"},
  {title: "Maxima", value: "Maxima"},
  {title: "Micra", value: "Micra"},
  {title: "Mid4", value: "Mid4"},
  {title: "MM", value: "MM"},
  {title: "Moco", value: "Moco"},
  {title: "Murano", value: "Murano"},
  {title: "Murano CrossCabriolet", value: "Murano CrossCabriolet"},
  {title: "Navara", value: "Navara"},
  {title: "Note", value: "Note"},
  {title: "NP300", value: "NP300"},
  {title: "NV", value: "NV"},
  {title: "NV200", value: "NV200"},
  {title: "Pathfinder", value: "Pathfinder"},
  {title: "Patrol", value: "Patrol"},
  {title: "Pickup", value: "Pickup"},
  {title: "Pintara", value: "Pintara"},
  {title: "Pixo", value: "Pixo"},
  {title: "Platina", value: "Platina"},
  {title: "Prairie", value: "Prairie"},
  {title: "Presea", value: "Presea"},
  {title: "President", value: "President"},
  {title: "Primera", value: "Primera"},
  {title: "Pulsar", value: "Pulsar"},
  {title: "Qashqai", value: "Qashqai"},
  {title: "Quest", value: "Quest"},
  {title: "R 390 GT1", value: "R 390 GT1"},
  {title: "R 391", value: "R 391"},
  {title: "Rasheen", value: "Rasheen"},
  {title: "Rogue", value: "Rogue"},
  {title: "Santana", value: "Santana"},
  {title: "Sedan", value: "Sedan"},
  {title: "Sentra", value: "Sentra"},
  {title: "Serena", value: "Serena"},
  {title: "Silvia", value: "Silvia"},
  {title: "Skyline", value: "Skyline"},
  {title: "Sport", value: "Sport"},
  {title: "Sports", value: "Sports"},
  {title: "Stagea", value: "Stagea"},
  {title: "Stanza", value: "Stanza"},
  {title: "Sunny", value: "Sunny"},
  {title: "SUT", value: "SUT"},
  {title: "Terrano", value: "Terrano"},
  {title: "Terrano II", value: "Terrano II"},
  {title: "Tiida", value: "Tiida"},
  {title: "Titan", value: "Titan"},
  {title: "Trailrunner", value: "Trailrunner"},
  {title: "Vanette", value: "Vanette"},
  {title: "Versa", value: "Versa"},
  {title: "Versa Note", value: "Versa Note"},
  {title: "Violet", value: "Violet"},
  {title: "X-Trail", value: "X-Trail"},
  {title: "Xterra", value: "Xterra"},
  {title: "XVL", value: "XVL"},
  {title: "Z", value: "Z"},
  {title: "Zaroot", value: "Zaroot"},
];

const peugeot = [
  {title: "1007", value: "1007"},
  {title: "104", value: "104"},
  {title: "106", value: "106"},
  {title: "107", value: "107"},
  {title: "202", value: "202"},
  {title: "203", value: "203"},
  {title: "204", value: "204"},
  {title: "205", value: "205"},
  {title: "206", value: "206"},
  {title: "207", value: "207"},
  {title: "3008", value: "3008"},
  {title: "304", value: "304"},
  {title: "305", value: "305"},
  {title: "306", value: "306"},
  {title: "307", value: "307"},
  {title: "308", value: "308"},
  {title: "309", value: "309"},
  {title: "4007", value: "4007"},
  {title: "4008", value: "4008"},
  {title: "403", value: "403"},
  {title: "404", value: "404"},
  {title: "405", value: "405"},
  {title: "406", value: "406"},
  {title: "407", value: "407"},
  {title: "408", value: "408"},
  {title: "5008", value: "5008"},
  {title: "504", value: "504"},
  {title: "504D", value: "504D"},
  {title: "505", value: "505"},
  {title: "508", value: "508"},
  {title: "604", value: "604"},
  {title: "605", value: "605"},
  {title: "607", value: "607"},
  {title: "806", value: "806"},
  {title: "807", value: "807"},
  {title: "907", value: "907"},
  {title: "Boxer", value: "Boxer"},
  {title: "Escapade", value: "Escapade"},
  {title: "Expert", value: "Expert"},
  {title: "H2O", value: "H2O"},
  {title: "iOn", value: "iOn"},
  {title: "Kart Up", value: "Kart Up"},
  {title: "Nautilus", value: "Nautilus"},
  {title: "Oxia", value: "Oxia"},
  {title: "Partner", value: "Partner"},
  {title: "Peugette", value: "Peugette"},
  {title: "Promethee", value: "Promethee"},
  {title: "Proxima", value: "Proxima"},
  {title: "Quasar", value: "Quasar"},
  {title: "RC", value: "RC"},
  {title: "RCZ", value: "RCZ"},
  {title: "Sesame", value: "Sesame"},
  {title: "Touareg", value: "Touareg"},
  {title: "Tulip", value: "Tulip"},
  {title: "Type 202", value: "Type 202"},
  {title: "Vroomster", value: "Vroomster"},
];

const pontiac = [
  {title: "1000", value: "1000"},
  {title: "6000", value: "6000"},
  {title: "Aztek", value: "Aztek"},
  {title: "Banshee", value: "Banshee"},
  {title: "Bonneville", value: "Bonneville"},
  {title: "Catalina", value: "Catalina"},
  {title: "Fiero", value: "Fiero"},
  {title: "Firebird", value: "Firebird"},
  {title: "Firehawk", value: "Firehawk"},
  {title: "G3", value: "G3"},
  {title: "G5", value: "G5"},
  {title: "G6", value: "G6"},
  {title: "G8", value: "G8"},
  {title: "GPX", value: "GPX"},
  {title: "Grand Am", value: "Grand Am"},
  {title: "Grand Prix", value: "Grand Prix"},
  {title: "Grand Safari", value: "Grand Safari"},
  {title: "Grande Parisienne", value: "Grande Parisienne"},
  {title: "GTO", value: "GTO"},
  {title: "Lemans", value: "Lemans"},
  {title: "Montana", value: "Montana"},
  {title: "Phoenix", value: "Phoenix"},
  {title: "Piranha", value: "Piranha"},
  {title: "Rageous", value: "Rageous"},
  {title: "Salsa", value: "Salsa"},
  {title: "Solstice", value: "Solstice"},
  {title: "Star Chief", value: "Star Chief"},
  {title: "Stinger", value: "Stinger"},
  {title: "Sunbird", value: "Sunbird"},
  {title: "Sunfire", value: "Sunfire"},
  {title: "SV 6", value: "SV 6"},
  {title: "Tempest", value: "Tempest"},
  {title: "Torrent", value: "Torrent"},
  {title: "Trans Am", value: "Trans Am"},
  {title: "Trans Sport", value: "Trans Sport"},
  {title: "Ventura", value: "Ventura"},
  {title: "Ventura II", value: "Ventura II"},
  {title: "Vibe", value: "Vibe"},
];

const porsche = [
  {title: "1300", value: "1300"},
  {title: "3400", value: "3400"},
  {title: "356", value: "356"},
  {title: "550 A", value: "550 A"},
  {title: "718", value: "718"},
  {title: "804", value: "804"},
  {title: "904", value: "904"},
  {title: "906", value: "906"},
  {title: "907", value: "907"},
  {title: "908", value: "908"},
  {title: "910", value: "910"},
  {title: "911", value: "911"},
  {title: "912", value: "912"},
  {title: "914", value: "914"},
  {title: "917", value: "917"},
  {title: "918 Spyder", value: "918 Spyder"},
  {title: "924", value: "924"},
  {title: "928", value: "928"},
  {title: "930", value: "930"},
  {title: "935", value: "935"},
  {title: "936", value: "936"},
  {title: "944", value: "944"},
  {title: "959", value: "959"},
  {title: "962", value: "962"},
  {title: "964", value: "964"},
  {title: "965", value: "965"},
  {title: "968", value: "968"},
  {title: "993", value: "993"},
  {title: "996", value: "996"},
  {title: "Boxster", value: "Boxster"},
  {title: "Boxter", value: "Boxter"},
  {title: "Carrera GT", value: "Carrera GT"},
  {title: "Cayenne", value: "Cayenne"},
  {title: "Cayman", value: "Cayman"},
  {title: "DP", value: "DP"},
  {title: "GT2", value: "GT2"},
  {title: "GT3", value: "GT3"},
  {title: "Karisma", value: "Karisma"},
  {title: "Kremer 935 K3", value: "Kremer 935 K3"},
  {title: "Macan", value: "Macan"},
  {title: "Mega Cabriolet Biturbo", value: "Mega Cabriolet Biturbo"},
  {title: "Pan Americana", value: "Pan Americana"},
  {title: "Panamera", value: "Panamera"},
  {title: "RGT", value: "RGT"},
  {title: "Tapiro", value: "Tapiro"},
];

const renault = [
  {title: "10", value: "10"},
  {title: "11", value: "11"},
  {title: "12", value: "12"},
  {title: "14", value: "14"},
  {title: "15", value: "15"},
  {title: "17", value: "17"},
  {title: "18", value: "18"},
  {title: "19", value: "19"},
  {title: "20", value: "20"},
  {title: "21", value: "21"},
  {title: "25", value: "25"},
  {title: "30", value: "30"},
  {title: "4", value: "4"},
  {title: "5", value: "5"},
  {title: "6", value: "6"},
  {title: "8", value: "8"},
  {title: "9", value: "9"},
  {title: "Alpine", value: "Alpine"},
  {title: "Argos", value: "Argos"},
  {title: "Avantime", value: "Avantime"},
  {title: "Be Bop", value: "Be Bop"},
  {title: "Caravelle", value: "Caravelle"},
  {title: "Clio", value: "Clio"},
  {title: "Colorale", value: "Colorale"},
  {title: "Dauphine", value: "Dauphine"},
  {title: "Dauphine Gordini", value: "Dauphine Gordini"},
  {title: "Duster", value: "Duster"},
  {title: "Ellypse", value: "Ellypse"},
  {title: "Espace", value: "Espace"},
  {title: "Espider", value: "Espider"},
  {title: "Etoile", value: "Etoile"},
  {title: "Express", value: "Express"},
  {title: "Fifties", value: "Fifties"},
  {title: "Floride", value: "Floride"},
  {title: "Fluence", value: "Fluence"},
  {title: "Fregate", value: "Fregate"},
  {title: "Fuego", value: "Fuego"},
  {title: "Grand Espace", value: "Grand Espace"},
  {title: "Grand Scenic", value: "Grand Scenic"},
  {title: "Helem", value: "Helem"},
  {title: "Juva", value: "Juva"},
  {title: "Kangoo", value: "Kangoo"},
  {title: "Koleos", value: "Koleos"},
  {title: "Laguna", value: "Laguna"},
  {title: "Latitude", value: "Latitude"},
  {title: "Logan", value: "Logan"},
  {title: "Ludo", value: "Ludo"},
  {title: "Megan", value: "Megan"},
  {title: "Megane", value: "Megane"},
  {title: "Modus", value: "Modus"},
  {title: "P55", value: "P55"},
  {title: "R5", value: "R5"},
  {title: "Racoon", value: "Racoon"},
  {title: "RE", value: "RE"},
  {title: "Rodeo", value: "Rodeo"},
  {title: "RS 11", value: "RS 11"},
  {title: "Safrane", value: "Safrane"},
  {title: "Sandero", value: "Sandero"},
  {title: "Scenic", value: "Scenic"},
  {title: "Scenic II", value: "Scenic II"},
  {title: "Siete", value: "Siete"},
  {title: "Spider", value: "Spider"},
  {title: "Sport Spider", value: "Sport Spider"},
  {title: "Super 5", value: "Super 5"},
  {title: "Symbol", value: "Symbol"},
  {title: "Talisman", value: "Talisman"},
  {title: "Thalia", value: "Thalia"},
  {title: "Trafic", value: "Trafic"},
  {title: "Twingo", value: "Twingo"},
  {title: "Twizy", value: "Twizy"},
  {title: "TXE", value: "TXE"},
  {title: "Vel Satis", value: "Vel Satis"},
  {title: "Wind", value: "Wind"},
  {title: "Zo", value: "Zo"},
  {title: "Zoe", value: "Zoe"},
  {title: "Zoom", value: "Zoom"},
];

const subaru = [
  {title: "1.8", value: "1.8"},
  {title: "1400", value: "1400"},
  {title: "360", value: "360"},
  {title: "Alfa", value: "Alfa"},
  {title: "B", value: "B"},
  {title: "B9 Tribeca", value: "B9 Tribeca"},
  {title: "Baja", value: "Baja"},
  {title: "BRZ", value: "BRZ"},
  {title: "Coupe", value: "Coupe"},
  {title: "DL", value: "DL"},
  {title: "FF-1", value: "FF-1"},
  {title: "Forester", value: "Forester"},
  {title: "G3X", value: "G3X"},
  {title: "HM-01", value: "HM-01"},
  {title: "Impreza", value: "Impreza"},
  {title: "Impreza WRX", value: "Impreza WRX"},
  {title: "Justy", value: "Justy"},
  {title: "K 111", value: "K 111"},
  {title: "Legacy", value: "Legacy"},
  {title: "Leone", value: "Leone"},
  {title: "Mini Jumbo", value: "Mini Jumbo"},
  {title: "Outback", value: "Outback"},
  {title: "Outback Sport", value: "Outback Sport"},
  {title: "Pleo", value: "Pleo"},
  {title: "R-2", value: "R-2"},
  {title: "R2", value: "R2"},
  {title: "Rex", value: "Rex"},
  {title: "STX", value: "STX"},
  {title: "SVX", value: "SVX"},
  {title: "Traviq", value: "Traviq"},
  {title: "Tribeca", value: "Tribeca"},
  {title: "Vivio", value: "Vivio"},
  {title: "WRX", value: "WRX"},
  {title: "WX 01", value: "WX 01"},
  {title: "XT", value: "XT"},
  {title: "XV", value: "XV"},
  {title: "XV Crosstrek", value: "XV Crosstrek"},
];

const tesla = [
  {title: "Model 3", value: "Model 3"},
  {title: "Model S", value: "Model S"},
  {title: "Model X", value: "Model X"},
  {title: "Model Y", value: "Model Y"},
  {title: "Roadster", value: "Roadster"},
];

const toyota = [
  {title: "1000", value: "1000"},
  {title: "105", value: "105"},
  {title: "2000GT", value: "2000GT"},
  {title: "4Runner", value: "4Runner"},
  {title: "AA", value: "AA"},
  {title: "Allion", value: "Allion"},
  {title: "Altezza", value: "Altezza"},
  {title: "Aristo", value: "Aristo"},
  {title: "Ateva", value: "Ateva"},
  {title: "Auris", value: "Auris"},
  {title: "Avalon", value: "Avalon"},
  {title: "Avalon Hybrid", value: "Avalon Hybrid"},
  {title: "Avanza", value: "Avanza"},
  {title: "Avensis", value: "Avensis"},
  {title: "Aygo", value: "Aygo"},
  {title: "Bandeirante", value: "Bandeirante"},
  {title: "BB", value: "BB"},
  {title: "Blizzard", value: "Blizzard"},
  {title: "Brevis", value: "Brevis"},
  {title: "Caldina", value: "Caldina"},
  {title: "Camry", value: "Camry"},
  {title: "Camry Hybrid", value: "Camry Hybrid"},
  {title: "Carina", value: "Carina"},
  {title: "Caserta", value: "Caserta"},
  {title: "Celica", value: "Celica"},
  {title: "Celsior", value: "Celsior"},
  {title: "Century", value: "Century"},
  {title: "Chaser", value: "Chaser"},
  {title: "Coaster", value: "Coaster"},
  {title: "Condor", value: "Condor"},
  {title: "Conquest", value: "Conquest"},
  {title: "Corolla", value: "Corolla"},
  {title: "Corona", value: "Corona"},
  {title: "Corsa", value: "Corsa"},
  {title: "Cressida", value: "Cressida"},
  {title: "Cresta", value: "Cresta"},
  {title: "Crown", value: "Crown"},
  {title: "Dyna", value: "Dyna"},
  {title: "Echo", value: "Echo"},
  {title: "ES 3", value: "ES 3"},
  {title: "F-1", value: "F-1"},
  {title: "FCHV 5", value: "FCHV 5"},
  {title: "FJ Cruiser", value: "FJ Cruiser"},
  {title: "Fortuner", value: "Fortuner"},
  {title: "FXS", value: "FXS"},
  {title: "GT1", value: "GT1"},
  {title: "Hi-Ace", value: "Hi-Ace"},
  {title: "Highlander", value: "Highlander"},
  {title: "Highlander Hybrid", value: "Highlander Hybrid"},
  {title: "Hilux", value: "Hilux"},
  {title: "HMV", value: "HMV"},
  {title: "Ipsum", value: "Ipsum"},
  {title: "iQ", value: "iQ"},
  {title: "Land Cruiser", value: "Land Cruiser"},
  {title: "Lexcen", value: "Lexcen"},
  {title: "Lite Ace", value: "Lite Ace"},
  {title: "Mark II", value: "Mark II"},
  {title: "Master RR", value: "Master RR"},
  {title: "Matrix", value: "Matrix"},
  {title: "Mega Cruiser", value: "Mega Cruiser"},
  {title: "Model F", value: "Model F"},
  {title: "MR-S", value: "MR-S"},
  {title: "MR2", value: "MR2"},
  {title: "MRJ", value: "MRJ"},
  {title: "Opa", value: "Opa"},
  {title: "Paseo", value: "Paseo"},
  {title: "Picnic", value: "Picnic"},
  {title: "Pod", value: "Pod"},
  {title: "Previa", value: "Previa"},
  {title: "Prius", value: "Prius"},
  {title: "Prius C", value: "Prius C"},
  {title: "Prius Plug-in", value: "Prius Plug-in"},
  {title: "Prius V", value: "Prius V"},
  {title: "Progress NC 300", value: "Progress NC 300"},
  {title: "Publica", value: "Publica"},
  {title: "Quantum", value: "Quantum"},
  {title: "Ractis", value: "Ractis"},
  {title: "RAV4", value: "RAV4"},
  {title: "RAV4 EV", value: "RAV4 EV"},
  {title: "Retro Cruiser", value: "Retro Cruiser"},
  {title: "RSC", value: "RSC"},
  {title: "RunX", value: "RunX"},
  {title: "SA", value: "SA"},
  {title: "Sequoia", value: "Sequoia"},
  {title: "Sera", value: "Sera"},
  {title: "Sienna", value: "Sienna"},
  {title: "Soarer", value: "Soarer"},
  {title: "Solara", value: "Solara"},
  {title: "Sparky", value: "Sparky"},
  {title: "Sport 800", value: "Sport 800"},
  {title: "Sprinter", value: "Sprinter"},
  {title: "Stallion", value: "Stallion"},
  {title: "Starlet", value: "Starlet"},
  {title: "Super", value: "Super"},
  {title: "Supra", value: "Supra"},
  {title: "Tacoma", value: "Tacoma"},
  {title: "Tazz", value: "Tazz"},
  {title: "Tercel", value: "Tercel"},
  {title: "Tundra", value: "Tundra"},
  {title: "Venture", value: "Venture"},
  {title: "Venza", value: "Venza"},
  {title: "Verossa", value: "Verossa"},
  {title: "Vitz", value: "Vitz"},
  {title: "Will", value: "Will"},
  {title: "Windom", value: "Windom"},
  {title: "XYR", value: "XYR"},
  {title: "Yaris", value: "Yaris"},
];

const volkswagen = [
  {title: "1 Litre", value: "1 Litre"},
  {title: "1302", value: "1302"},
  {title: "1303", value: "1303"},
  {title: "1500", value: "1500"},
  {title: "1600", value: "1600"},
  {title: "181", value: "181"},
  {title: "411", value: "411"},
  {title: "AAC", value: "AAC"},
  {title: "Beetle", value: "Beetle"},
  {title: "Beetle Convertible", value: "Beetle Convertible"},
  {title: "Bora", value: "Bora"},
  {title: "Cabriolet", value: "Cabriolet"},
  {title: "Caddy", value: "Caddy"},
  {title: "Caravelle", value: "Caravelle"},
  {title: "CC", value: "CC"},
  {title: "Citi", value: "Citi"},
  {title: "Commercial", value: "Commercial"},
  {title: "Concept C", value: "Concept C"},
  {title: "Concept T", value: "Concept T"},
  {title: "Corrado", value: "Corrado"},
  {title: "Derby", value: "Derby"},
  {title: "e-Golf", value: "e-Golf"},
  {title: "Eos", value: "Eos"},
  {title: "Eurovan", value: "Eurovan"},
  {title: "Fox", value: "Fox"},
  {title: "Fusca", value: "Fusca"},
  {title: "GLI", value: "GLI"},
  {title: "Gol", value: "Gol"},
  {title: "Golf", value: "Golf"},
  {title: "Golf GTI", value: "Golf GTI"},
  {title: "Golf R", value: "Golf R"},
  {title: "Golf SportWagen", value: "Golf SportWagen"},
  {title: "GTD", value: "GTD"},
  {title: "GTI", value: "GTI"},
  {title: "Hac", value: "Hac"},
  {title: "Iltis", value: "Iltis"},
  {title: "Jetta", value: "Jetta"},
  {title: "Jetta GLI", value: "Jetta GLI"},
  {title: "Jetta Hybrid", value: "Jetta Hybrid"},
  {title: "Jetta SportWagen", value: "Jetta SportWagen"},
  {title: "K 70", value: "K 70"},
  {title: "Karmann-Ghia", value: "Karmann-Ghia"},
  {title: "Kombi", value: "Kombi"},
  {title: "LT 35 HR Panel Van", value: "LT 35 HR Panel Van"},
  {title: "Lupo", value: "Lupo"},
  {title: "Magellan", value: "Magellan"},
  {title: "Microbus", value: "Microbus"},
  {title: "Multivan", value: "Multivan"},
  {title: "New Beetle", value: "New Beetle"},
  {title: "Parati", value: "Parati"},
  {title: "Passat", value: "Passat"},
  {title: "Phaeton", value: "Phaeton"},
  {title: "Pickup", value: "Pickup"},
  {title: "Polo", value: "Polo"},
  {title: "Quantum", value: "Quantum"},
  {title: "Rabbit", value: "Rabbit"},
  {title: "Routan", value: "Routan"},
  {title: "Santana", value: "Santana"},
  {title: "Schwimmwagen", value: "Schwimmwagen"},
  {title: "Scirocco", value: "Scirocco"},
  {title: "Sedan", value: "Sedan"},
  {title: "Sharan", value: "Sharan"},
  {title: "SP", value: "SP"},
  {title: "SP2", value: "SP2"},
  {title: "T5", value: "T5"},
  {title: "Tiguan", value: "Tiguan"},
  {title: "Touareg", value: "Touareg"},
  {title: "Touran", value: "Touran"},
  {title: "Transporter", value: "Transporter"},
  {title: "Type 3 Squareback", value: "Type 3 Squareback"},
  {title: "up", value: "up"},
  {title: "Vento", value: "Vento"},
  {title: "W12", value: "W12"},
];

const volvo = [
  {title: "120", value: "120"},
  {title: "122", value: "122"},
  {title: "140", value: "140"},
  {title: "144", value: "144"},
  {title: "145", value: "145"},
  {title: "164", value: "164"},
  {title: "1800", value: "1800"},
  {title: "220", value: "220"},
  {title: "240", value: "240"},
  {title: "242", value: "242"},
  {title: "244", value: "244"},
  {title: "245", value: "245"},
  {title: "260", value: "260"},
  {title: "264", value: "264"},
  {title: "265", value: "265"},
  {title: "343", value: "343"},
  {title: "360", value: "360"},
  {title: "440", value: "440"},
  {title: "460", value: "460"},
  {title: "480", value: "480"},
  {title: "66", value: "66"},
  {title: "740", value: "740"},
  {title: "760", value: "760"},
  {title: "780", value: "780"},
  {title: "850", value: "850"},
  {title: "940", value: "940"},
  {title: "960", value: "960"},
  {title: "C30", value: "C30"},
  {title: "C70", value: "C70"},
  {title: "Duett", value: "Duett"},
  {title: "Hatric", value: "Hatric"},
  {title: "P 1800", value: "P 1800"},
  {title: "P 1900", value: "P 1900"},
  {title: "P 210 Duett", value: "P 210 Duett"},
  {title: "PV", value: "PV"},
  {title: "PV 544 1.8", value: "PV 544 1.8"},
  {title: "PV 60", value: "PV 60"},
  {title: "PV 801-10", value: "PV 801-10"},
  {title: "S40", value: "S40"},
  {title: "S60", value: "S60"},
  {title: "S70", value: "S70"},
  {title: "S80", value: "S80"},
  {title: "S90", value: "S90"},
  {title: "SCC", value: "SCC"},
  {title: "V40", value: "V40"},
  {title: "V50", value: "V50"},
  {title: "V60", value: "V60"},
  {title: "V60 Cross Country", value: "V60 Cross Country"},
  {title: "V70", value: "V70"},
  {title: "V90", value: "V90"},
  {title: "X670", value: "X670"},
  {title: "XC60", value: "XC60"},
  {title: "XC70", value: "XC70"},
  {title: "XC90", value: "XC90"},
  {title: "YCC", value: "YCC"},
];

export const models = {
  audi,
  bmw,
  buick,
  cadillac,
  chevrolet,
  citroen,
  dodge,
  ferrari,
  ford,
  GMC,
  honda,
  hyundai,
  jaguar,
  jeep,
  kia,
  lexus,
  lincoln,
  mazda,
  "mercedes-benz": mercedes,
  mitsubishi,
  nissan,
  peugeot,
  pontiac,
  porsche,
  renault,
  subaru,
  tesla,
  toyota,
  volkswagen,
  volvo,
};
